# Generated by Django 4.2.1 on 2023-05-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API_ChirpChat", "0003_alter_usuario_id_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="id_foto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="API_ChirpChat.foto",
            ),
        ),
    ]
