# Generated by Django 4.2.1 on 2023-05-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_ChirpChat", "0004_alter_usuario_id_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foto",
            name="url",
        ),
        migrations.AddField(
            model_name="foto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="fotos/"),
        ),
    ]
