# Generated by Django 4.2.1 on 2023-05-07 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API_ChirpChat", "0005_remove_foto_url_foto_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foto",
            name="titulo",
        ),
    ]
