# Generated by Django 4.2.1 on 2023-05-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_ChirpChat", "0006_remove_foto_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
