# Generated by Django 4.2.1 on 2023-05-07 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API_ChirpChat", "0007_alter_foto_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicacion",
            name="titulo",
        ),
    ]
