# Generated by Django 4.2.1 on 2023-05-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API_ChirpChat", "0008_remove_publicacion_titulo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicacion",
            name="id_foto",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="id_foto",
        ),
        migrations.AddField(
            model_name="publicacion",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.DeleteModel(
            name="foto",
        ),
    ]
